(() => {
'use strict';
const F=window.POKESLEEP_FOOD_COLOR_FEATURES;
const REF_W=691,REF_H=1536,TOP_ANCHOR=10,MAIN_ANCHOR=559,TOP_HEADER_MIN_GREEN=260;
const FOOD_BOXES={food1:[290,220,390,300],food2:[405,220,505,300],food3:[520,220,620,300]};
const TARGET_MAX=[44,48,52,56,60,64], variantCache=new Map(), sourceCanvasCache=new Map();
function greenAnchorInfo(canvas,refY=TOP_ANCHOR){const ctx=canvas.getContext('2d',{willReadFrequently:true}),w=canvas.width,h=canvas.height,d=ctx.getImageData(0,0,w,h).data,target=refY*h/REF_H,lo=Math.max(0,Math.floor(target-h*.07)),hi=Math.min(h,Math.ceil(target+h*.07));let by=Math.round(target),best=-1;for(let y=lo;y<hi;y++){let c=0;for(let x=0;x<w;x+=2){const i=(y*w+x)*4,r=d[i],g=d[i+1],b=d[i+2];if(g>=145&&g-r>=35&&g-b>=20)c++;}if(c>best){best=c;by=y;}}return {y:by,best,target};}
function cropFood(canvas,key){const [x1,y1,x2,y2]=FOOD_BOXES[key],h=canvas.height,sy=h/REF_H,sx=canvas.width/REF_W,top=greenAnchorInfo(canvas),main=top.best>=TOP_HEADER_MIN_GREEN?null:greenAnchorInfo(canvas,MAIN_ANCHOR),dy=top.best>=TOP_HEADER_MIN_GREEN?top.y-TOP_ANCHOR*sy:(main&&main.best>=TOP_HEADER_MIN_GREEN?main.y-MAIN_ANCHOR*sy:0);const ax=Math.max(0,Math.round(x1*sx)),ay=Math.max(0,Math.round(y1*sy+dy)),bx=Math.min(canvas.width,Math.round(x2*sx)),by=Math.min(h,Math.round(y2*sy+dy));const out=document.createElement('canvas');out.width=Math.max(1,bx-ax);out.height=Math.max(1,by-ay);out.getContext('2d',{willReadFrequently:true}).drawImage(canvas,ax,ay,bx-ax,by-ay,0,0,out.width,out.height);return out;}
function sourceCanvas(label){if(sourceCanvasCache.has(label))return sourceCanvasCache.get(label);const f=F.foods[label];if(!f)return null;const c=document.createElement('canvas');c.width=f.w;c.height=f.h;const ctx=c.getContext('2d',{willReadFrequently:true}),im=ctx.createImageData(f.w,f.h);im.data.set(f.rgba);ctx.putImageData(im,0,0);sourceCanvasCache.set(label,c);return c;}
function variants(label){if(variantCache.has(label))return variantCache.get(label);const src=sourceCanvas(label),f=F.foods[label],out=[];if(!src)return out;for(const target of TARGET_MAX){const sc=target/Math.max(f.w,f.h),w=Math.max(2,Math.round(f.w*sc)),h=Math.max(2,Math.round(f.h*sc)),c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(src,0,0,w,h);out.push({w,h,data:ctx.getImageData(0,0,w,h).data});}variantCache.set(label,out);return out;}
function median(a){if(!a.length)return 255;a.sort((x,y)=>x-y);const m=a.length>>1;return a.length%2?a[m]:(a[m-1]+a[m])/2;}
function cropData(canvas){const ctx=canvas.getContext('2d',{willReadFrequently:true}),w=canvas.width,h=canvas.height,d=ctx.getImageData(0,0,w,h).data,rs=[],gs=[],bs=[];for(let y=2;y<Math.min(68,h);y++)for(let x=5;x<Math.min(82,w);x++){const i=(y*w+x)*4,r=d[i],g=d[i+1],b=d[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b),mean=(r+g+b)/3;if(mean>210&&mx-mn<55){rs.push(r);gs.push(g);bs.push(b);}}return {w,h,d,bg:[median(rs),median(gs),median(bs)]};}
function scoreVariant(crop,v){const {w:W,h:H,d,bg}=crop,{w,h,data:t}=v;if(w>=W||h>=H)return -2;const bx=Math.round((W-w)/2),by=Math.round((H-h)/2)-5;let best=-2;for(let y=Math.max(0,by-8);y<=Math.min(H-h,by+8);y+=4)for(let x=Math.max(0,bx-10);x<=Math.min(W-w,bx+10);x+=4){let dot=0,nd=0,nv=0,n=0;for(let ty=0;ty<h;ty++)for(let tx=0;tx<w;tx++){const ti=(ty*w+tx)*4,a=t[ti+3]/255;if(a<=.08)continue;const si=((y+ty)*W+x+tx)*4;for(let c=0;c<3;c++){const dv=crop.d[si+c]-bg[c],vv=(t[ti+c]-bg[c])*a;dot+=dv*vv;nd+=dv*dv;nv+=vv*vv;}n++;}if(n&&nd>0&&nv>0){const s=dot/Math.sqrt(nd*nv);if(s>best)best=s;}}return best;}
function scoreShapeVariant(crop,v){const {w:W,h:H,d,bg}=crop,{w,h,data:t}=v;if(w>=W||h>=H)return -2;const bx=Math.round((W-w)/2),by=Math.round((H-h)/2)-5;let best=-2;for(let y=Math.max(0,by-8);y<=Math.min(H-h,by+8);y+=4)for(let x=Math.max(0,bx-10);x<=Math.min(W-w,bx+10);x+=4){let inter=0,tm=0,cm=0;for(let ty=0;ty<h;ty++)for(let tx=0;tx<w;tx++){const ti=(ty*w+tx)*4,isTemplate=t[ti+3]/255>.08,si=((y+ty)*W+x+tx)*4,dr=crop.d[si]-bg[0],dg=crop.d[si+1]-bg[1],db=crop.d[si+2]-bg[2],isCrop=Math.sqrt(dr*dr+dg*dg+db*db)>25;if(isTemplate)tm++;if(isCrop)cm++;if(isTemplate&&isCrop)inter++;}if(tm+cm){const s=2*inter/(tm+cm);if(s>best)best=s;}}return best;}
function matchCanvas(canvas,allowed){const crop=cropData(canvas),vals=[];for(const label of allowed||[]){let best=-2;for(const v of variants(label)){const s=scoreVariant(crop,v);if(s>best)best=s;}vals.push({name:label,score:best});}vals.sort((a,b)=>b.score-a.score);const top=vals[0]||{name:'',score:0},second=vals[1]||{name:'',score:0};return {name:top.name,score:top.score,second:second.name,secondScore:second.score,margin:top.score-second.score,ranking:vals};}
function matchDimmedFoodIcon(canvas,allowed,maxColorScore=Infinity){const color=matchCanvas(canvas,allowed);if(!Array.isArray(color.ranking)||color.ranking.length<2||color.margin>.04||color.score>maxColorScore)return color;const crop=cropData(canvas),shape=[];for(const label of allowed||[]){let best=-2;for(const v of variants(label)){const s=scoreShapeVariant(crop,v);if(s>best)best=s;}shape.push({name:label,score:best});}shape.sort((a,b)=>b.score-a.score);const top=shape[0]||{name:'',score:0},second=shape[1]||{name:'',score:0},shapeMargin=top.score-second.score;if(top.name&&top.name===color.second&&shapeMargin>=.04){return {name:top.name,score:top.score,second:second.name,secondScore:second.score,margin:shapeMargin,ranking:shape,dimmedShapeArbitration:true,colorRanking:color.ranking};}return color;}
function uniqueProfiles(hits){const out=[];for(const h of hits||[]){const k=h.foods.join('\u0001');if(!out.some(x=>x.key===k))out.push({key:k,foods:[...h.foods]});}return out;}
function resolveSlots(screenCanvas,inference,level){const ps=uniqueProfiles(inference?.hits||[]),keys=['food1','food2','food3'];return keys.map((key,i)=>{const allowed=[...new Set(ps.map(p=>p.foods[i]).filter(Boolean))];if(allowed.length===1)return {name:allowed[0],score:1,second:'',secondScore:0,margin:1,method:'db-inferred',allowed};const crop=cropFood(screenCanvas,key),isDimmedFood2=i===1&&Number.isFinite(level)&&level<30,isDimmedFood3=i===2&&Number.isFinite(level)&&level<60,m=isDimmedFood2?matchDimmedFoodIcon(crop,allowed):isDimmedFood3?matchDimmedFoodIcon(crop,allowed,.82):matchCanvas(crop,allowed);return {...m,method:'image',allowed};});}
window.POKESLEEP_FOOD_MATCHER={cropFood,matchCanvas,resolveSlots};
})();
