(()=>{
'use strict';
const RUNNER_ID='candidate122-device-regression-runner-v1';
const CANDIDATE_RELEASE='2026-10-08-candidate122-review-safety-guard';
const $=s=>document.querySelector(s);
const state={registry:null,manifests:new Map(),running:false,current:null,lastReport:null,log:[]};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function timestamp(d=new Date()){const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`;}
function deviceLabel(){const ua=navigator.userAgent||'';if(/iPhone/.test(ua)&&/Safari/.test(ua)&&!/CriOS|FxiOS|EdgiOS/.test(ua))return'iPhone-Safari';if(/Android/.test(ua)&&/Chrome\//.test(ua))return'Android-Chrome';if(/iPad/.test(ua)&&/Safari/.test(ua))return'iPad-Safari';return'Other';}
function environment(){return {capturedAt:new Date().toISOString(),deviceGate:deviceLabel(),userAgent:navigator.userAgent||'',platform:navigator.platform||'',vendor:navigator.vendor||'',language:navigator.language||'',hardwareConcurrency:navigator.hardwareConcurrency||null,deviceMemory:navigator.deviceMemory||null,maxTouchPoints:navigator.maxTouchPoints||0,screen:{width:screen.width,height:screen.height,pixelRatio:window.devicePixelRatio||1},viewport:{width:innerWidth,height:innerHeight},standalone:!!matchMedia?.('(display-mode: standalone)').matches,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||''};}
function log(msg){const row={at:new Date().toISOString(),message:String(msg)};state.log.push(row);const el=$('#regLog');if(el){el.textContent+=`[${row.at.slice(11,19)}] ${row.message}\n`;el.scrollTop=el.scrollHeight;}console.log('[regression]',msg);}
function api(){const a=window.__BUKKOMI_REGRESSION_API__;if(!a)throw new Error('Candidate122 regression API is not ready');return a;}
function fieldActual(diagResult,field){const p=diagResult?.parsed||{},c=diagResult?.classification||{};if(field==='species')return c.candidates?.length===1?c.candidates[0]:'';if(field==='nickname')return p.nickname??'';if(field==='level')return p.level??null;if(field==='sp')return p.sp??null;if(field==='helpSeconds')return p.helpSeconds??null;if(field==='carry')return p.carry??null;if(field==='skillLevel')return p.skillLevel??null;if(field==='mainSkill')return p.mainSkillOutput||p.mainSkill||'';if(field==='nature')return p.nature||'';if(field==='subskills')return p.subskills||[];if(field==='foods')return (diagResult?.foods||[]).map(x=>x?.name||'');return null;}
function normalizeMainSkillForGolden(v){let s=String(v??'').replace(/\s+\(/g,'(');return /^おてつだいブースト\((ほのお|みず|でんき)\)$/.test(s)?'おてつだいブースト':s;}
function normalizeAbsentSlot(v){return v==='―'||v==='—'||v==='-'?'':v;}
function sameField(field,a,b){
 if(field==='mainSkill')return normalizeMainSkillForGolden(a)===normalizeMainSkillForGolden(b);
 if(field==='subskills'||field==='foods'){return Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&a.every((v,i)=>normalizeAbsentSlot(v)===normalizeAbsentSlot(b[i]));}
 if(Array.isArray(a)||Array.isArray(b))return Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&a.every((v,i)=>v===b[i]);
 return a===b;
}
function reviewCount(rs){if(!rs)return 0;let n=0;for(const k of ['species','nickname','level','skillLevel','mainSkill','nature'])if(rs[k])n++;if(Array.isArray(rs.foods))n+=rs.foods.filter(Boolean).length;else if(rs.foods)n++;if(Array.isArray(rs.subskills))n+=rs.subskills.filter(Boolean).length;else if(rs.subskills)n++;return n;}
function grade(record,result){
 const fields={};let wrong=0;
 for(const field of record.scoreFields||[]){const expected=record.expected[field],actual=fieldActual(result,field),ok=sameField(field,actual,expected);fields[field]={ok,expected,actual};if(!ok)wrong++;}
 const processingError=result?.processingError||null, reviews=reviewCount(result?.reviewState);
 let verdict;if(processingError)verdict='PROCESSING_ERROR';else if(wrong)verdict='FAIL_VALUE';else if(reviews)verdict='CORRECT_NEEDS_REVIEW';else verdict='PASS_AUTO';
 return {assetId:record.assetId,file:record.file,verdict,wrongFieldCount:wrong,reviewCount:reviews,fields,reviewState:result?.reviewState||null,processingError,elapsedMs:result?.elapsedMs??null,classification:result?.classification||null,inference:result?.inference||null};
}
function summarize(cases){const s={total:cases.length,passAuto:0,correctNeedsReview:0,failValue:0,processingError:0,unprocessed:0,wrongFields:{},reviewFields:{},elapsedMs:0};for(const c of cases){if(c.verdict==='PASS_AUTO')s.passAuto++;else if(c.verdict==='CORRECT_NEEDS_REVIEW')s.correctNeedsReview++;else if(c.verdict==='FAIL_VALUE')s.failValue++;else if(c.verdict==='PROCESSING_ERROR')s.processingError++;else s.unprocessed++;for(const [k,v] of Object.entries(c.fields||{}))if(!v.ok)s.wrongFields[k]=(s.wrongFields[k]||0)+1;const rs=c.reviewState||{};for(const k of ['species','nickname','level','skillLevel','mainSkill','nature'])if(rs[k])s.reviewFields[k]=(s.reviewFields[k]||0)+1;if(Array.isArray(rs.foods))rs.foods.forEach((v,i)=>{if(v)s.reviewFields[`food${i+1}`]=(s.reviewFields[`food${i+1}`]||0)+1;});if(Array.isArray(rs.subskills))rs.subskills.forEach((v,i)=>{if(v)s.reviewFields[`sub${[10,25,50,70,80][i]}`]=(s.reviewFields[`sub${[10,25,50,70,80][i]}`]||0)+1;});s.elapsedMs+=Number(c.elapsedMs)||0;}s.autoPassRate=s.total?+(s.passAuto/s.total*100).toFixed(2):0;s.valueCorrectRate=s.total?+((s.passAuto+s.correctNeedsReview)/s.total*100).toFixed(2):0;return s;}
async function loadRegistry(){state.registry=await (await fetch('corpora/registry.json',{cache:'no-store'})).json();for(const c of state.registry.corpora){const m=await (await fetch(c.manifest,{cache:'no-store'})).json();state.manifests.set(c.id,m);}renderCorpusButtons();}
function renderCorpusButtons(){const host=$('#regCorpora');host.innerHTML='';for(const c of state.registry.corpora){const b=document.createElement('button');b.className='reg-btn';b.disabled=state.running;b.textContent=`${c.label} (${c.count})${c.status==='PENDING_FUTURE_DELETE'?' [legacy]':''}`;b.onclick=()=>runSuite([c.id],c.id);host.appendChild(b);}const real=state.registry.corpora.filter(c=>c.category==='owner'||c.category==='real-user').map(c=>c.id);const all=state.registry.corpora.map(c=>c.id);const b1=document.createElement('button');b1.className='reg-btn primary';b1.disabled=state.running;b1.textContent='主要corpusを実行';b1.onclick=()=>runSuite(real,'primary-corpora');host.prepend(b1);const b2=document.createElement('button');b2.className='reg-btn';b2.disabled=state.running;b2.textContent='全corpusを実行';b2.onclick=()=>runSuite(all,'all-corpora');host.appendChild(b2);}
async function fetchAsFile(record){const res=await fetch(record.imagePath,{cache:'no-store'});if(!res.ok)throw new Error(`${record.file}: HTTP ${res.status}`);const blob=await res.blob();return new File([blob],record.file,{type:blob.type||(/\.jpe?g$/i.test(record.file)?'image/jpeg':'image/png'),lastModified:0});}
async function loadFiles(records){const files=new Array(records.length);let next=0,done=0;const workers=Array.from({length:Math.min(4,records.length)},async()=>{while(true){const i=next++;if(i>=records.length)return;files[i]=await fetchAsFile(records[i]);done++;setStatus(`画像読込 ${done}/${records.length}`);}});await Promise.all(workers);return files;}
function setStatus(s){const e=$('#regStatus');if(e)e.textContent=s;}
async function runRecords(manifest,records,globalCases,partitionDiagnostics,partitionLabel){
 let cursor=0,sub=0;
 while(cursor<records.length){sub++;const slice=records.slice(cursor);log(`${manifest.corpusId} ${partitionLabel} subrun${sub}: ${slice.length}枚を準備`);const files=await loadFiles(slice);const before=api().state().ocrMemoryGuard;const run=await api().runFiles(files);const diag=run.diagnostics;const after=api().state().ocrMemoryGuard;partitionDiagnostics.push({corpusId:manifest.corpusId,partition:partitionLabel,subrun:sub,startOffset:cursor,inputCount:slice.length,ok:run.ok,paused:run.paused,pauseIndex:run.pauseIndex,memoryGuardBefore:before,memoryGuardAfter:after,diagnostics:diag});
 const byFile=new Map((diag.results||[]).map(x=>[x.file,x]));let processed=0,lastProcessed=-1;
 for(let i=0;i<slice.length;i++){const rec=slice[i],rr=byFile.get(rec.file);if(!rr)continue;globalCases.push({...grade(rec,rr),corpusId:manifest.corpusId,priority:manifest.priority,partition:partitionLabel});processed++;lastProcessed=i;}
 if(!run.paused){if(processed<slice.length){for(let i=0;i<slice.length;i++){const rec=slice[i];if(byFile.has(rec.file))continue;globalCases.push({assetId:rec.assetId,file:rec.file,corpusId:manifest.corpusId,priority:manifest.priority,partition:partitionLabel,verdict:'UNPROCESSED',reason:'run-completed-without-result',fields:{}});}cursor=records.length;}else cursor=records.length;
 }else{
  const failedAt=Number.isInteger(run.pauseIndex)?run.pauseIndex:lastProcessed;
  if(failedAt<0){for(const rec of slice)globalCases.push({assetId:rec.assetId,file:rec.file,corpusId:manifest.corpusId,priority:manifest.priority,partition:partitionLabel,verdict:'UNPROCESSED',reason:'paused-without-progress',fields:{}});cursor=records.length;}else cursor+=failedAt+1;
 }
 await api().reset();await sleep(50);
 }
}
async function runCorpus(manifest,report){const max=api().maxFiles||100,records=manifest.records;const partitions=[];for(let i=0;i<records.length;i+=max)partitions.push(records.slice(i,i+max));log(`${manifest.corpusId}: ${records.length}枚 / ${partitions.length} partition`);for(let i=0;i<partitions.length;i++){setStatus(`${manifest.corpusId} ${i+1}/${partitions.length}`);await runRecords(manifest,partitions[i],report.cases,report.partitionDiagnostics,`${i+1}/${partitions.length}`);}const own=report.cases.filter(x=>x.corpusId===manifest.corpusId);report.corpusSummaries[manifest.corpusId]=summarize(own);log(`${manifest.corpusId}: auto ${report.corpusSummaries[manifest.corpusId].passAuto}/${own.length}, review ${report.corpusSummaries[manifest.corpusId].correctNeedsReview}, value fail ${report.corpusSummaries[manifest.corpusId].failValue}, processing ${report.corpusSummaries[manifest.corpusId].processingError}`);renderSummary(report);}
async function runSuite(ids,label){if(state.running)return;state.running=true;state.log=[];$('#regLog').textContent='';renderCorpusButtons();const started=new Date();const report={schema:1,runnerId:RUNNER_ID,candidateReleaseId:CANDIDATE_RELEASE,suite:label,startedAt:started.toISOString(),finishedAt:null,environment:environment(),corpusDefinitions:ids.map(id=>{const m=state.manifests.get(id);return {corpusId:m.corpusId,label:m.label,category:m.category,priority:m.priority,status:m.status,count:m.count};}),corpusSummaries:{},summary:null,cases:[],partitionDiagnostics:[],runnerLog:state.log};state.current=report;try{log(`START ${label} / ${report.environment.deviceGate}`);for(const id of ids)await runCorpus(state.manifests.get(id),report);report.summary=summarize(report.cases);report.finishedAt=new Date().toISOString();state.lastReport=report;setStatus('完了');log(`DONE ${label}: ${report.summary.passAuto}/${report.summary.total} auto PASS`);renderSummary(report);$('#regDownload').disabled=false;}catch(e){console.error(e);report.finishedAt=new Date().toISOString();report.fatalError={name:e?.name||'Error',message:e?.message||String(e),stack:e?.stack||''};report.summary=summarize(report.cases);state.lastReport=report;setStatus('エラー');log(`FATAL: ${e?.message||e}`);renderSummary(report);$('#regDownload').disabled=false;}finally{state.running=false;renderCorpusButtons();try{await api().reset();}catch(_){} }}
function renderSummary(report){const e=$('#regSummary');if(!e)return;const s=report.summary||summarize(report.cases);const rows=Object.entries(report.corpusSummaries).map(([id,x])=>`<tr><td>${esc(id)}</td><td>${x.total}</td><td>${x.passAuto}</td><td>${x.correctNeedsReview}</td><td>${x.failValue}</td><td>${x.processingError}</td></tr>`).join('');e.innerHTML=`<div class="reg-kpis"><b>総数 ${s.total}</b><span>自動PASS ${s.passAuto}</span><span>正解+要確認 ${s.correctNeedsReview}</span><span>値FAIL ${s.failValue}</span><span>処理FAIL ${s.processingError}</span></div><table><thead><tr><th>corpus</th><th>total</th><th>auto</th><th>review</th><th>value fail</th><th>proc fail</th></tr></thead><tbody>${rows}</tbody></table>`;}
function download(){const r=state.lastReport;if(!r)return;const name=`candidate122_regression_${r.suite}_${r.environment.deviceGate}_${timestamp()}.json`;const blob=new Blob([JSON.stringify(r,null,2)],{type:'application/json;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{a.remove();URL.revokeObjectURL(u);},1500);}
function injectUi(){const style=document.createElement('style');style.textContent=`.reg-panel{position:relative;z-index:20;margin:12px auto;max-width:1100px;padding:14px;border:2px solid #111;border-radius:14px;background:#fff}.reg-title{font-size:20px;font-weight:800}.reg-note{font-size:13px;line-height:1.5}.reg-actions{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.reg-btn{padding:10px 12px;border:1px solid #bbb;border-radius:10px;background:#f7f7f7;font-weight:700}.reg-btn.primary{background:#111;color:#fff}.reg-kpis{display:flex;gap:12px;flex-wrap:wrap;margin:8px 0}.reg-panel table{border-collapse:collapse;width:100%;font-size:12px}.reg-panel th,.reg-panel td{border:1px solid #ddd;padding:4px}.reg-log{white-space:pre-wrap;max-height:180px;overflow:auto;background:#111;color:#eee;padding:8px;border-radius:8px;font:11px/1.4 monospace}.reg-status{font-weight:700}.reg-download{padding:10px 12px}.reg-danger{color:#a00;font-weight:700}`;document.head.appendChild(style);const panel=document.createElement('section');panel.className='reg-panel';panel.innerHTML=`<div class="reg-title">Candidate122 実機回帰 Runner v1</div><div class="reg-note"><span class="reg-danger">TEST ONLY</span> — Candidate122のreview-safetyコードを使い、canonical画像を実画像→OCR→parse→classifier→reviewまで通します。主要Gate: iPhone Safari / Android Chrome。meka142は100+42に分割（本番MAX_FILES=100準拠）。runner用IndexedDBは本番と分離しています。</div><div id="regCorpora" class="reg-actions"></div><div class="reg-actions"><button id="regDownload" class="reg-download" disabled>結果JSONを保存</button><span id="regStatus" class="reg-status">準備中…</span></div><div id="regSummary"></div><pre id="regLog" class="reg-log"></pre>`;document.body.insertBefore(panel,document.body.firstChild);$('#regDownload').addEventListener('click',download);}
async function init(){injectUi();try{if(document.getElementById('tipsDialog')?.open)document.getElementById('tipsDialog').close();await loadRegistry();setStatus(`準備完了 / ${deviceLabel()}`);log(`API ${api().releaseId} / MAX_FILES=${api().maxFiles}`);}catch(e){console.error(e);setStatus('初期化失敗');log(e?.message||String(e));}}
if(window.__BUKKOMI_REGRESSION_API__)void init();else window.addEventListener('bukkomi-regression-api-ready',()=>void init(),{once:true});
})();
